INSERT INTO "app_comercio_computador" ("idProducto","marca","precioUnitario","cpu","ram","hdd") VALUES (1,'acer',427968,'amd',32,256);
INSERT INTO "app_comercio_computador" ("idProducto","marca","precioUnitario","cpu","ram","hdd") VALUES (2,'lenovo',535674,'amd',32,1024);
INSERT INTO "app_comercio_computador" ("idProducto","marca","precioUnitario","cpu","ram","hdd") VALUES (3,'hp',414640,'intel',32,512);
INSERT INTO "app_comercio_computador" ("idProducto","marca","precioUnitario","cpu","ram","hdd") VALUES (6,'acer',440502,'intel',8,1024);
INSERT INTO "app_comercio_computador" ("idProducto","marca","precioUnitario","cpu","ram","hdd") VALUES (12,'lenovo',415398,'intel',16,512);
INSERT INTO "app_comercio_computador" ("idProducto","marca","precioUnitario","cpu","ram","hdd") VALUES (13,'samsung',573560,'amd',16,512);
INSERT INTO "app_comercio_computador" ("idProducto","marca","precioUnitario","cpu","ram","hdd") VALUES (14,'lenovo',540345,'intel',16,512);
INSERT INTO "app_comercio_computador" ("idProducto","marca","precioUnitario","cpu","ram","hdd") VALUES (17,'lg',515126,'amd',16,256);
INSERT INTO "app_comercio_computador" ("idProducto","marca","precioUnitario","cpu","ram","hdd") VALUES (18,'lenovo',405135,'amd',8,1024);
INSERT INTO "app_comercio_computador" ("idProducto","marca","precioUnitario","cpu","ram","hdd") VALUES (22,'samsung',550621,'amd',16,512);
INSERT INTO "app_comercio_computador" ("idProducto","marca","precioUnitario","cpu","ram","hdd") VALUES (26,'lg',401966,'intel',16,256);
INSERT INTO "app_comercio_computador" ("idProducto","marca","precioUnitario","cpu","ram","hdd") VALUES (27,'dell',521419,'amd',32,512);
INSERT INTO "app_comercio_computador" ("idProducto","marca","precioUnitario","cpu","ram","hdd") VALUES (36,'lenovo',411784,'intel',32,256);
INSERT INTO "app_comercio_computador" ("idProducto","marca","precioUnitario","cpu","ram","hdd") VALUES (43,'hp',544009,'intel',8,512);
INSERT INTO "app_comercio_computador" ("idProducto","marca","precioUnitario","cpu","ram","hdd") VALUES (50,'lenovo',429456,'amd',32,512);
INSERT INTO "app_comercio_computador" ("idProducto","marca","precioUnitario","cpu","ram","hdd") VALUES (51,'samsung',508966,'intel',8,1024);
INSERT INTO "app_comercio_computador" ("idProducto","marca","precioUnitario","cpu","ram","hdd") VALUES (53,'samsung',553877,'amd',32,256);
INSERT INTO "app_comercio_computador" ("idProducto","marca","precioUnitario","cpu","ram","hdd") VALUES (54,'acer',406407,'amd',32,512);
INSERT INTO "app_comercio_computador" ("idProducto","marca","precioUnitario","cpu","ram","hdd") VALUES (57,'lg',476226,'intel',32,1024);
INSERT INTO "app_comercio_computador" ("idProducto","marca","precioUnitario","cpu","ram","hdd") VALUES (58,'hp',483038,'amd',16,256);
INSERT INTO "app_comercio_computador" ("idProducto","marca","precioUnitario","cpu","ram","hdd") VALUES (60,'hp',550385,'amd',8,256);
INSERT INTO "app_comercio_computador" ("idProducto","marca","precioUnitario","cpu","ram","hdd") VALUES (62,'samsung',542575,'amd',32,512);
INSERT INTO "app_comercio_computador" ("idProducto","marca","precioUnitario","cpu","ram","hdd") VALUES (65,'hp',406969,'amd',8,1024);
INSERT INTO "app_comercio_computador" ("idProducto","marca","precioUnitario","cpu","ram","hdd") VALUES (67,'hp',503556,'amd',8,1024);
INSERT INTO "app_comercio_computador" ("idProducto","marca","precioUnitario","cpu","ram","hdd") VALUES (71,'acer',432265,'amd',8,512);
INSERT INTO "app_comercio_computador" ("idProducto","marca","precioUnitario","cpu","ram","hdd") VALUES (73,'samsung',464850,'amd',16,512);
INSERT INTO "app_comercio_computador" ("idProducto","marca","precioUnitario","cpu","ram","hdd") VALUES (75,'lenovo',574043,'intel',32,512);
INSERT INTO "app_comercio_computador" ("idProducto","marca","precioUnitario","cpu","ram","hdd") VALUES (78,'dell',490991,'amd',8,1024);
INSERT INTO "app_comercio_computador" ("idProducto","marca","precioUnitario","cpu","ram","hdd") VALUES (79,'lg',547627,'amd',16,1024);
INSERT INTO "app_comercio_computador" ("idProducto","marca","precioUnitario","cpu","ram","hdd") VALUES (81,'samsung',560614,'intel',8,1024);
INSERT INTO "app_comercio_computador" ("idProducto","marca","precioUnitario","cpu","ram","hdd") VALUES (84,'lenovo',439580,'intel',32,512);
INSERT INTO "app_comercio_computador" ("idProducto","marca","precioUnitario","cpu","ram","hdd") VALUES (86,'acer',427756,'intel',16,1024);
INSERT INTO "app_comercio_computador" ("idProducto","marca","precioUnitario","cpu","ram","hdd") VALUES (90,'acer',515807,'amd',16,1024);
INSERT INTO "app_comercio_computador" ("idProducto","marca","precioUnitario","cpu","ram","hdd") VALUES (92,'hp',502847,'intel',8,512);
INSERT INTO "app_comercio_computador" ("idProducto","marca","precioUnitario","cpu","ram","hdd") VALUES (98,'lg',498296,'intel',32,256);
INSERT INTO "app_comercio_monitor" ("idProducto","marca","precioUnitario","resolucion") VALUES (0,'hp',264491,'32');
INSERT INTO "app_comercio_monitor" ("idProducto","marca","precioUnitario","resolucion") VALUES (5,'acer',272587,'32');
INSERT INTO "app_comercio_monitor" ("idProducto","marca","precioUnitario","resolucion") VALUES (7,'hp',191393,'40');
INSERT INTO "app_comercio_monitor" ("idProducto","marca","precioUnitario","resolucion") VALUES (8,'lg',187087,'60');
INSERT INTO "app_comercio_monitor" ("idProducto","marca","precioUnitario","resolucion") VALUES (10,'lg',274128,'60');
INSERT INTO "app_comercio_monitor" ("idProducto","marca","precioUnitario","resolucion") VALUES (11,'dell',208844,'32');
INSERT INTO "app_comercio_monitor" ("idProducto","marca","precioUnitario","resolucion") VALUES (15,'hp',245973,'60');
INSERT INTO "app_comercio_monitor" ("idProducto","marca","precioUnitario","resolucion") VALUES (19,'samsung',265114,'60');
INSERT INTO "app_comercio_monitor" ("idProducto","marca","precioUnitario","resolucion") VALUES (20,'acer',234475,'32');
INSERT INTO "app_comercio_monitor" ("idProducto","marca","precioUnitario","resolucion") VALUES (21,'lg',220249,'40');
INSERT INTO "app_comercio_monitor" ("idProducto","marca","precioUnitario","resolucion") VALUES (23,'dell',238798,'60');
INSERT INTO "app_comercio_monitor" ("idProducto","marca","precioUnitario","resolucion") VALUES (25,'samsung',270128,'40');
INSERT INTO "app_comercio_monitor" ("idProducto","marca","precioUnitario","resolucion") VALUES (32,'dell',290238,'40');
INSERT INTO "app_comercio_monitor" ("idProducto","marca","precioUnitario","resolucion") VALUES (33,'dell',210880,'32');
INSERT INTO "app_comercio_monitor" ("idProducto","marca","precioUnitario","resolucion") VALUES (34,'acer',238757,'60');
INSERT INTO "app_comercio_monitor" ("idProducto","marca","precioUnitario","resolucion") VALUES (38,'hp',257455,'40');
INSERT INTO "app_comercio_monitor" ("idProducto","marca","precioUnitario","resolucion") VALUES (39,'dell',257650,'32');
INSERT INTO "app_comercio_monitor" ("idProducto","marca","precioUnitario","resolucion") VALUES (40,'acer',189040,'60');
INSERT INTO "app_comercio_monitor" ("idProducto","marca","precioUnitario","resolucion") VALUES (46,'hp',274185,'32');
INSERT INTO "app_comercio_monitor" ("idProducto","marca","precioUnitario","resolucion") VALUES (49,'lenovo',171544,'60');
INSERT INTO "app_comercio_monitor" ("idProducto","marca","precioUnitario","resolucion") VALUES (52,'hp',259374,'32');
INSERT INTO "app_comercio_monitor" ("idProducto","marca","precioUnitario","resolucion") VALUES (55,'samsung',229657,'60');
INSERT INTO "app_comercio_monitor" ("idProducto","marca","precioUnitario","resolucion") VALUES (56,'dell',237472,'40');
INSERT INTO "app_comercio_monitor" ("idProducto","marca","precioUnitario","resolucion") VALUES (59,'dell',209171,'60');
INSERT INTO "app_comercio_monitor" ("idProducto","marca","precioUnitario","resolucion") VALUES (61,'lg',202669,'32');
INSERT INTO "app_comercio_monitor" ("idProducto","marca","precioUnitario","resolucion") VALUES (64,'lg',212030,'60');
INSERT INTO "app_comercio_monitor" ("idProducto","marca","precioUnitario","resolucion") VALUES (66,'samsung',230625,'60');
INSERT INTO "app_comercio_monitor" ("idProducto","marca","precioUnitario","resolucion") VALUES (69,'lg',282976,'60');
INSERT INTO "app_comercio_monitor" ("idProducto","marca","precioUnitario","resolucion") VALUES (70,'lenovo',287574,'40');
INSERT INTO "app_comercio_monitor" ("idProducto","marca","precioUnitario","resolucion") VALUES (72,'samsung',275786,'60');
INSERT INTO "app_comercio_monitor" ("idProducto","marca","precioUnitario","resolucion") VALUES (74,'samsung',211789,'40');
INSERT INTO "app_comercio_monitor" ("idProducto","marca","precioUnitario","resolucion") VALUES (76,'hp',268624,'40');
INSERT INTO "app_comercio_monitor" ("idProducto","marca","precioUnitario","resolucion") VALUES (77,'lenovo',224883,'32');
INSERT INTO "app_comercio_monitor" ("idProducto","marca","precioUnitario","resolucion") VALUES (80,'hp',251148,'40');
INSERT INTO "app_comercio_monitor" ("idProducto","marca","precioUnitario","resolucion") VALUES (82,'hp',292226,'32');
INSERT INTO "app_comercio_monitor" ("idProducto","marca","precioUnitario","resolucion") VALUES (87,'lenovo',276827,'32');
INSERT INTO "app_comercio_monitor" ("idProducto","marca","precioUnitario","resolucion") VALUES (91,'samsung',177223,'40');
INSERT INTO "app_comercio_monitor" ("idProducto","marca","precioUnitario","resolucion") VALUES (94,'acer',226692,'32');
INSERT INTO "app_comercio_monitor" ("idProducto","marca","precioUnitario","resolucion") VALUES (95,'samsung',242297,'32');
INSERT INTO "app_comercio_monitor" ("idProducto","marca","precioUnitario","resolucion") VALUES (96,'samsung',181196,'32');
INSERT INTO "app_comercio_monitor" ("idProducto","marca","precioUnitario","resolucion") VALUES (99,'lenovo',257653,'32');
INSERT INTO "app_comercio_mouse" ("idProducto","marca","precioUnitario","wireless") VALUES (4,'lg',14463,'true');
INSERT INTO "app_comercio_mouse" ("idProducto","marca","precioUnitario","wireless") VALUES (9,'dell',26262,'false');
INSERT INTO "app_comercio_mouse" ("idProducto","marca","precioUnitario","wireless") VALUES (16,'samsung',62604,'false');
INSERT INTO "app_comercio_mouse" ("idProducto","marca","precioUnitario","wireless") VALUES (24,'lg',42256,'false');
INSERT INTO "app_comercio_mouse" ("idProducto","marca","precioUnitario","wireless") VALUES (28,'samsung',25091,'true');
INSERT INTO "app_comercio_mouse" ("idProducto","marca","precioUnitario","wireless") VALUES (29,'hp',65496,'true');
INSERT INTO "app_comercio_mouse" ("idProducto","marca","precioUnitario","wireless") VALUES (30,'lenovo',52981,'false');
INSERT INTO "app_comercio_mouse" ("idProducto","marca","precioUnitario","wireless") VALUES (31,'samsung',39663,'false');
INSERT INTO "app_comercio_mouse" ("idProducto","marca","precioUnitario","wireless") VALUES (35,'hp',83913,'true');
INSERT INTO "app_comercio_mouse" ("idProducto","marca","precioUnitario","wireless") VALUES (37,'dell',95912,'true');
INSERT INTO "app_comercio_mouse" ("idProducto","marca","precioUnitario","wireless") VALUES (41,'lg',33915,'false');
INSERT INTO "app_comercio_mouse" ("idProducto","marca","precioUnitario","wireless") VALUES (42,'hp',39189,'false');
INSERT INTO "app_comercio_mouse" ("idProducto","marca","precioUnitario","wireless") VALUES (44,'lenovo',99308,'false');
INSERT INTO "app_comercio_mouse" ("idProducto","marca","precioUnitario","wireless") VALUES (45,'lenovo',91148,'true');
INSERT INTO "app_comercio_mouse" ("idProducto","marca","precioUnitario","wireless") VALUES (47,'lenovo',86316,'true');
INSERT INTO "app_comercio_mouse" ("idProducto","marca","precioUnitario","wireless") VALUES (48,'acer',69865,'true');
INSERT INTO "app_comercio_mouse" ("idProducto","marca","precioUnitario","wireless") VALUES (63,'samsung',99468,'true');
INSERT INTO "app_comercio_mouse" ("idProducto","marca","precioUnitario","wireless") VALUES (68,'acer',82775,'false');
INSERT INTO "app_comercio_mouse" ("idProducto","marca","precioUnitario","wireless") VALUES (83,'lg',64570,'true');
INSERT INTO "app_comercio_mouse" ("idProducto","marca","precioUnitario","wireless") VALUES (85,'hp',46443,'false');
INSERT INTO "app_comercio_mouse" ("idProducto","marca","precioUnitario","wireless") VALUES (88,'lg',34481,'false');
INSERT INTO "app_comercio_mouse" ("idProducto","marca","precioUnitario","wireless") VALUES (89,'samsung',16283,'false');
INSERT INTO "app_comercio_mouse" ("idProducto","marca","precioUnitario","wireless") VALUES (93,'lenovo',44017,'true');
INSERT INTO "app_comercio_mouse" ("idProducto","marca","precioUnitario","wireless") VALUES (97,'samsung',37192,'false');
INSERT INTO "app_comercio_cliente" ("rut","nombre","direccion","celular","email") VALUES (9684802,'Otis Portwood','328 17th Street',908929960,'otis.portwood@gmail.com');
INSERT INTO "app_comercio_cliente" ("rut","nombre","direccion","celular","email") VALUES (25788583,'Curtis Lay  ','169 Avenida Drive',930936290,'curtis.lay@gmail.com');
INSERT INTO "app_comercio_cliente" ("rut","nombre","direccion","celular","email") VALUES (23270174,'Gary Bernal ','222 Quince Street',971661108,'gary.bernal@gmail.com');
INSERT INTO "app_comercio_cliente" ("rut","nombre","direccion","celular","email") VALUES (23966891,'Frankie Cox ','4231 Miramonte Way',961450882,'frankie.cox@gmail.com');
INSERT INTO "app_comercio_cliente" ("rut","nombre","direccion","celular","email") VALUES (7998894,'Nancy Madden','2337 Nebraska Avenue',985411779,'nancy.madden@gmail.com');
INSERT INTO "app_comercio_cliente" ("rut","nombre","direccion","celular","email") VALUES (13272380,'Arnita Li   ','5430 Brookdale Avenue',953556540,'arnita.li@gmail.com');
INSERT INTO "app_comercio_cliente" ("rut","nombre","direccion","celular","email") VALUES (18459021,'Timothy Coffin','1452 55th Avenue',955059754,'timothy.coffin@gmail.com');
INSERT INTO "app_comercio_cliente" ("rut","nombre","direccion","celular","email") VALUES (29073463,'Jeff Barnard','2064 West Columbia Way',964659139,'jeff.barnard@gmail.com');
INSERT INTO "app_comercio_cliente" ("rut","nombre","direccion","celular","email") VALUES (25803804,'Manuel Wilkes','40902 Ingersoll Terrace',988427962,'manuel.wilkes@gmail.com');
INSERT INTO "app_comercio_cliente" ("rut","nombre","direccion","celular","email") VALUES (6645094,'Michael Morlino','22538 6th Street',995652563,'michael.morlino@gmail.com');
INSERT INTO "app_comercio_cliente" ("rut","nombre","direccion","celular","email") VALUES (15959655,'Brenda Capuano','24647 Patricia Court',999997417,'brenda.capuano@gmail.com');
INSERT INTO "app_comercio_cliente" ("rut","nombre","direccion","celular","email") VALUES (6478300,'Barbara Willis','1209 Parker Street',932240479,'barbara.willis@gmail.com');
INSERT INTO "app_comercio_cliente" ("rut","nombre","direccion","celular","email") VALUES (20659313,'Miriam Cho','6431 Shattuck Avenue',909002610,'miriam.cho@gmail.com');
INSERT INTO "app_comercio_cliente" ("rut","nombre","direccion","celular","email") VALUES (25534723,'Cathy Williams','222 Quince Street',951656584,'cathy.williams@gmail.com');
INSERT INTO "app_comercio_cliente" ("rut","nombre","direccion","celular","email") VALUES (14299611,'Dawn Myers','6100 Bullard Drive',992651729,'dawn.myers@gmail.com');
INSERT INTO "app_comercio_cliente" ("rut","nombre","direccion","celular","email") VALUES (29005108,'Sherri Lamke','46710 Crawford Street',989802136,'sherri.lamke@gmail.com');
INSERT INTO "app_comercio_cliente" ("rut","nombre","direccion","celular","email") VALUES (10925760,'Marion Williams','1528 Spruce Street',915369495,'marion.williams@gmail.com');
INSERT INTO "app_comercio_cliente" ("rut","nombre","direccion","celular","email") VALUES (10650185,'Tom Hunt','136 Acacia Drive',967336865,'tom.hunt@gmail.com');
INSERT INTO "app_comercio_cliente" ("rut","nombre","direccion","celular","email") VALUES (10571450,'Joe Nail','31130 Meadowbrook Avenue',985648061,'joe.nail@gmail.com');
INSERT INTO "app_comercio_cliente" ("rut","nombre","direccion","celular","email") VALUES (18306833,'Raymond Ford','2902 Flint Street',928672845,'raymond.ford@gmail.com');
INSERT INTO "app_comercio_cliente" ("rut","nombre","direccion","celular","email") VALUES (11124206,'Fay Wallace','2750 Gilmore Lane',936052356,'fay.wallace@gmail.com');
INSERT INTO "app_comercio_cliente" ("rut","nombre","direccion","celular","email") VALUES (15493150,'Janice Mcnulty','2522 Fountain Avenue',903321469,'janice.mcnulty@gmail.com');
INSERT INTO "app_comercio_cliente" ("rut","nombre","direccion","celular","email") VALUES (29952071,'Julius Schultz','2750 Gilmore Lane',958325603,'julius.schultz@gmail.com');
INSERT INTO "app_comercio_cliente" ("rut","nombre","direccion","celular","email") VALUES (28269335,'Rick Jackson','928 Wright Avenue',982330265,'rick.jackson@gmail.com');
INSERT INTO "app_comercio_cliente" ("rut","nombre","direccion","celular","email") VALUES (8815168,'Richard Mcgee','465 Humboldt Way',914236170,'richard.mcgee@gmail.com');
INSERT INTO "app_comercio_cliente" ("rut","nombre","direccion","celular","email") VALUES (27050045,'Carol Pharis','5130 Morris Way',900284182,'carol.pharis@gmail.com');
INSERT INTO "app_comercio_cliente" ("rut","nombre","direccion","celular","email") VALUES (22157326,'Michelle Jones','4971 Janet Court',918702789,'michelle.jones@gmail.com');
INSERT INTO "app_comercio_cliente" ("rut","nombre","direccion","celular","email") VALUES (25637123,'Angela Smith','1238 Roanwood Way',933828560,'angela.smith@gmail.com');
INSERT INTO "app_comercio_cliente" ("rut","nombre","direccion","celular","email") VALUES (17280406,'Stephanie Cowell','10400 Royal Oak Road',932814840,'stephanie.cowell@gmail.com');
INSERT INTO "app_comercio_cliente" ("rut","nombre","direccion","celular","email") VALUES (9118971,'Claude Peterson','856 Milton Street',945666835,'claude.peterson@gmail.com');
INSERT INTO "app_comercio_cliente" ("rut","nombre","direccion","celular","email") VALUES (10310471,'Iris Smith','1300 Lemos Lane',971335248,'iris.smith@gmail.com');
INSERT INTO "app_comercio_cliente" ("rut","nombre","direccion","celular","email") VALUES (7160085,'Amy Scaggs','10881 Northforde Drive',949382838,'amy.scaggs@gmail.com');
INSERT INTO "app_comercio_cliente" ("rut","nombre","direccion","celular","email") VALUES (8598750,'Nicole Harper','775 47th Street',967346752,'nicole.harper@gmail.com');
INSERT INTO "app_comercio_cliente" ("rut","nombre","direccion","celular","email") VALUES (20649628,'Christopher Hannah','31353 Santa Elena Way',924147559,'christopher.hannah@gmail.com');
INSERT INTO "app_comercio_cliente" ("rut","nombre","direccion","celular","email") VALUES (16457202,'Douglas Jimerson','560 Penstock Drive',933126402,'douglas.jimerson@gmail.com');
INSERT INTO "app_comercio_cliente" ("rut","nombre","direccion","celular","email") VALUES (17933207,'Larry Miller','1890 Orchard View Road',938009083,'larry.miller@gmail.com');
INSERT INTO "app_comercio_cliente" ("rut","nombre","direccion","celular","email") VALUES (23841910,'Steven Bohannon','22538 6th Street',965183385,'steven.bohannon@gmail.com');
INSERT INTO "app_comercio_cliente" ("rut","nombre","direccion","celular","email") VALUES (22086639,'Virgina Brock','2337 Nebraska Avenue',916272647,'virgina.brock@gmail.com');
INSERT INTO "app_comercio_cliente" ("rut","nombre","direccion","celular","email") VALUES (24025106,'Billy Heltzel','4438 Maine Avenue',900644488,'billy.heltzel@gmail.com');
INSERT INTO "app_comercio_cliente" ("rut","nombre","direccion","celular","email") VALUES (15036748,'Harold Harman','2522 Fountain Avenue',988161223,'harold.harman@gmail.com');
INSERT INTO "app_comercio_cliente" ("rut","nombre","direccion","celular","email") VALUES (28793397,'Kenneth Meczywor','5396 North Reese Avenue',903540802,'kenneth.meczywor@gmail.com');
INSERT INTO "app_comercio_cliente" ("rut","nombre","direccion","celular","email") VALUES (25234205,'Patrick Sylvester','1761 Thousand Oaks Boulevard',964030080,'patrick.sylvester@gmail.com');
INSERT INTO "app_comercio_cliente" ("rut","nombre","direccion","celular","email") VALUES (13059079,'Gerald Rollins','942 Lewis Road',910435858,'gerald.rollins@gmail.com');
INSERT INTO "app_comercio_cliente" ("rut","nombre","direccion","celular","email") VALUES (29413697,'Amanda Mikolajczyk','328 17th Street',990034552,'amanda.mikolajczyk@gmail.com');
INSERT INTO "app_comercio_cliente" ("rut","nombre","direccion","celular","email") VALUES (12573591,'Karen Mclavrin','6057 Griffith Avenue',987459169,'karen.mclavrin@gmail.com');
INSERT INTO "app_comercio_cliente" ("rut","nombre","direccion","celular","email") VALUES (23715870,'Timothy Toothaker','3027 Badger Drive',967828527,'timothy.toothaker@gmail.com');
INSERT INTO "app_comercio_cliente" ("rut","nombre","direccion","celular","email") VALUES (28182982,'Mason Atkinson','238 La Salle Avenue',948243863,'mason.atkinson@gmail.com');
INSERT INTO "app_comercio_cliente" ("rut","nombre","direccion","celular","email") VALUES (11940349,'Willie Brown','1040 University Avenue',931748390,'willie.brown@gmail.com');
INSERT INTO "app_comercio_cliente" ("rut","nombre","direccion","celular","email") VALUES (17201877,'Mark Wiser','33300 Mission Boulevard',931615679,'mark.wiser@gmail.com');
INSERT INTO "app_comercio_cliente" ("rut","nombre","direccion","celular","email") VALUES (24139990,'Charles Wilson','5410 McLean Drive',990135495,'charles.wilson@gmail.com');
INSERT INTO "app_comercio_cliente" ("rut","nombre","direccion","celular","email") VALUES (24416668,'Henry Young','3189 Main Street',959909449,'henry.young@gmail.com');
INSERT INTO "app_comercio_cliente" ("rut","nombre","direccion","celular","email") VALUES (21871262,'Carrie Fink','682 Brighton Way',930778362,'carrie.fink@gmail.com');
INSERT INTO "app_comercio_cliente" ("rut","nombre","direccion","celular","email") VALUES (14812746,'Mary Pastorin','7800 River Mist Avenue',987408807,'mary.pastorin@gmail.com');
INSERT INTO "app_comercio_cliente" ("rut","nombre","direccion","celular","email") VALUES (29470712,'Anthony Hambright','37122 Contra Costa Avenue',949592530,'anthony.hambright@gmail.com');
INSERT INTO "app_comercio_cliente" ("rut","nombre","direccion","celular","email") VALUES (17758500,'Vincent White','928 Wright Avenue',933773767,'vincent.white@gmail.com');
INSERT INTO "app_comercio_cliente" ("rut","nombre","direccion","celular","email") VALUES (13214721,'Mildred Valdez','4920 Quonset Drive',982291591,'mildred.valdez@gmail.com');
INSERT INTO "app_comercio_cliente" ("rut","nombre","direccion","celular","email") VALUES (27110014,'Verona Smith','3008 Russell Street',926980285,'verona.smith@gmail.com');
INSERT INTO "app_comercio_cliente" ("rut","nombre","direccion","celular","email") VALUES (16213545,'Elizabeth Ruggles','1300 Lemos Lane',919478129,'elizabeth.ruggles@gmail.com');
INSERT INTO "app_comercio_cliente" ("rut","nombre","direccion","celular","email") VALUES (15365732,'Lee Deason','1040 University Avenue',900451638,'lee.deason@gmail.com');
INSERT INTO "app_comercio_cliente" ("rut","nombre","direccion","celular","email") VALUES (11122614,'Derrick Moller','4439 Gale Street',907045043,'derrick.moller@gmail.com');
INSERT INTO "app_comercio_cliente" ("rut","nombre","direccion","celular","email") VALUES (14568679,'Daniel San Martin','Volcan Sollipulli',956319019,'dsanmartins@gmail.com');
INSERT INTO "app_comercio_cliente" ("rut","nombre","direccion","celular","email") VALUES (64298823,'Gustavo','Ecuador',953503952,'gustavo@gmail.com');
INSERT INTO "app_comercio_cliente" ("rut","nombre","direccion","celular","email") VALUES (123434,'Gustavo','sadfsa',123123123,'sdfsdf@gmail.com');
INSERT INTO "app_comercio_cliente" ("rut","nombre","direccion","celular","email") VALUES (43534234,'Pedro','Ecuador',334342042340,'pedro@gmail.com');
